### ISSUE TITLE
Setup build & docker for release

### ISSUE THREAD

**Issue by pedronauck** [FuelLabs/data-systems#15]
## Description

We need to configure a process of build and publish that will be used for all packages inside the repo. The idea is build a Docker image on Github Registry on each release that can be used altogether with the binaries within the Github Release and publish on Crates.io.

This process is very similar with what already [have been doing on Fuel Core](https://github.com/FuelLabs/fuel-core/blob/master/.github/workflows/ci.yml#L220-L563).

## Tasks
- [x] Configure Docker structure for build [(use this as base standard)](https://github.com/FuelLabs/fuel-core/tree/master/deployment)
- [x] Add step on `Release` action for build and publish a Docker image
- [x] Add step on `Release` action for build and publish Rust binaries within the automated Github Release
- [x] Add step on `Release` action for build and publish on Crates.io

**Comment by pedronauck** [comment]
Closed #31
