### ISSUE TITLE
Setup basic tooling on the repository

### ISSUE THREAD

**Issue by pedronauck** [FuelLabs/data-systems#2]
## Tasks

  - [x] Set up basic tooling for CI checks
  - [x] Create basic workspace structure
  - [x] Add README and CONTRIBUTING documentation
  - [x] Improve GitHub-related configuration
  - [x] Remove main source files and adjust project license
  - [x] Improve Makefile
  - [x] Set up Commitizen for standardized commit messages
  - [x] Update pre-commit configuration
  - [x] Adjust GitHub actions and pre-commit hooks
