### ISSUE TITLE
Implement Subject and Filters structure in the SDK

### ISSUE THREAD

**Issue by pedronauck** [FuelLabs/data-systems#92]
## Description
Implement the `Subject` enum and `Filter` structure in the SDK to allow users to specify and filter different types of data streams. This will enable fine-grained control over subscriptions and data retrieval.

```rust
use fuel_streams::{
    stream::{Filter, Subscription},
};

fn main() {
    let tx_filter = Filter::<Subject::Transactions>::new()
        .with_status(TransactionStatus::Success)
        .with_type(TransactionType::Script);
}
```

> [!IMPORTANT]
The end result of the filter should be the related subject pattern as `&str` that will be used in the NATS stream.

## Tasks
- [ ] Create a `Subject` enum with variants for different data types (e.g., Blocks, Transactions)
- [ ] Implement a `Filter` struct that is generic over the `Subject` type
- [ ] Add methods to `Filter` for setting various filtering criteria
- [ ] Implement filter combination logic (e.g., chaining multiple filters)
- [ ] Create specific filter methods for each `Subject` variant
- [ ] Implement conversion from `Filter` to NATS subject strings
- [ ] Write unit tests for `Subject` and `Filter` implementations
- [ ] Create integration tests demonstrating filter usage with `Subscription`

## Technical Details
- Use Rust's type system to ensure type safety when creating filters for specific subjects
- Implement the builder pattern for `Filter` to allow for a fluent API
- Ensure efficient conversion from `Filter` to NATS subject strings
- Consider using traits to define common filter behaviors across different subject types

## Additional Notes
- The implementation should support filters like those in the example:
  `Filter::<Subject::Transactions>::new().with_status(TransactionStatus::Success).with_type(TransactionType::Script)`
- Ensure the API is intuitive and easy to use
- Consider future extensibility when designing the `Subject` and `Filter` structures

## Definition of Done
- [ ] Code implemented
- [ ] Unit tests written and passing
- [ ] Integration tests (if applicable) written and passing
- [ ] Documentation updated
- [ ] Code reviewed
