### ISSUE TITLE
Implement Client in the SDK

### ISSUE THREAD

**Issue by pedronauck** [FuelLabs/data-systems#94]
## Description
Design and implement the Client component in the SDK, which will manage connections to the NATS server and provide a clean API for establishing and maintaining these connections.

```rust
use fuel_streams::conn::{Client, ConnectionResult};

#[tokio::main]
async fn main() -> ConnectionResult<()> {
    let server = Client::new("stream.fuel.network").await?;
    Ok(())
}
```

## Tasks
- [ ] Create a Client struct with necessary fields (e.g., connection, options)
- [ ] Implement a new() method for initializing a Client instance
- [ ] Create a connect() method to establish a connection to the NATS server
- [ ] Add a status() method to check the current connection status
- [ ] Develop error handling for connection issues
- [ ] Implement ConnectionResult type alias
- [ ] Write unit tests for all Client methods
- [ ] Create integration tests against NATS server

## Technical Details
- Ensure thread safety for concurrent access
- Implement proper error types and error propagation
- Consider using the builder pattern for configurable connection options

## Definition of Done
- [ ] Code implemented
- [ ] Unit tests written and passing
- [ ] Integration tests (if applicable) written and passing
- [ ] Documentation updated
- [ ] Code reviewed
