### ISSUE TITLE
Setup cargo audit

### ISSUE THREAD

**Issue by pedronauck** [FuelLabs/data-systems#95]
## Description
Integrate cargo audit into the project workflow to automatically check for security vulnerabilities in dependencies.

## Tasks
- [x] Install cargo audit in the development environment
- [x] Add cargo audit to the CI pipeline
- [x] Configure cargo audit settings (if necessary)
- [x] Create a process for regularly running cargo audits and addressing findings (get inspiration from what [we have in fuel-core](https://github.com/fuellabs/fuel-core))

## Technical Details
Use cargo audit from https://github.com/rustsec/cargo-audit

## Additional Notes
Consider setting up scheduled runs of cargo audit to catch new vulnerabilities promptly.

## Definition of Done
- [ ] Code implemented
- [ ] Unit tests written and passing
- [ ] Integration tests (if applicable) written and passing
- [ ] Documentation updated
- [ ] Code reviewed
