### ISSUE TITLE
Update to use v0.32 of fuel-core on Publisher

### ISSUE THREAD

**Issue by pedronauck** [FuelLabs/data-systems#96]
## Description
Update the Publisher crate to use fuel-core version 0.32

## Tasks
- [x] Update fuel-core dependency to version 0.32 in Cargo.toml
- [x] Adjust Publisher code to accommodate any breaking changes in fuel-core v0.32
- [x] Update any affected tests
- [x] Verify functionality with the new fuel-core version

## Technical Details
Refer to fuel-core v0.32 changelog for specific changes and new features.

## Definition of Done
- [x] Code implemented
- [x] Unit tests written and passing
- [x] Integration tests (if applicable) written and passing
- [x] Documentation updated
- [x] Code reviewed

**Comment by pedronauck** [comment]
Closed on #111
